In [2]:
print("Hello World")

Hello World


In [3]:
print("hello world")
print("hello CS")

hello world
hello CS


In [4]:
print("hello world \nhello CS")

hello world 
hello CS


In [5]:
#이건 주석

In [6]:
# 반지름이 7.1 인 구의 표면적

print("구의 면적은 : ",4*3.14*7.1**2)

구의 면적은 :  633.1496


In [12]:
4*3.14*7.1**2
print("서은혁")

서은혁


In [13]:
area = 4*3.14*7.1**2

In [14]:
print(area)

633.1496


In [15]:
면적 = 4*3.14*7.1**2

In [16]:
print(면적)

633.1496


In [17]:
type(area)

float

In [18]:
temp = 1

In [19]:
type(temp)

int

In [20]:
temp2 = 1.0

In [21]:
type(temp2)

float

In [22]:
name = "서은혁"

In [23]:
print(name)

서은혁


In [24]:
name2 = "두번째"

In [25]:
name + name2

'서은혁두번째'

In [26]:
print(name+name2)

서은혁두번째


In [27]:
name + temp

TypeError: must be str, not int

In [29]:
name + str(temp)

'서은혁1'

In [30]:
print(temp)

1


In [31]:
print(name, temp)

서은혁 1


In [45]:
name3 = name + name2

In [46]:
name3

'서은혁두번째'

In [47]:
name3[0]

'서'

In [49]:
name3[3]

'두'

In [52]:
name3[-1]

'째'

In [53]:
name3[2:4]

'혁두'

In [54]:
name3[2:-1]

'혁두번'

In [55]:
name3[2:]

'혁두번째'

List 형식

In [56]:
pet_list = ["강아지", "고양이", "거북이", "뱀"]

In [57]:
print(pet_list)

['강아지', '고양이', '거북이', '뱀']


In [58]:
type(pet_list)

list

In [59]:
len(pet_list)

4

In [60]:
pet_list[0]

'강아지'

In [61]:
type(pet_list[0])

str

In [62]:
pet_list[0][1]

'아'

In [63]:
list2 = [2,3,5]

In [64]:
list2[0]

2

In [68]:
list3 = [2, '강아지', '서은혁']

In [69]:
print(list3)

[2, '강아지', '서은혁']


In [70]:
list4 = [2, '강아지', [1,2,3]]

In [71]:
print(list4)

[2, '강아지', [1, 2, 3]]


In [73]:
list4[2][-1]

3

In [77]:
pet_list[1] = "코끼리"

In [78]:
print(pet_list)

['강아지', '코끼리', '거북이', '뱀']


In [79]:
pet_list.append("고양이")

In [80]:
pet_list

['강아지', '코끼리', '거북이', '뱀', '고양이']

In [82]:
list2.append("서은혁")

In [83]:
list2

[2, 3, 5, '서은혁']

In [84]:
list2.append([4,5,6,"고양이"])

In [85]:
list2

[2, 3, 5, '서은혁', [4, 5, 6, '고양이']]

In [86]:
list2.extend([4,5,6,"고양이"])

In [87]:
list2

[2, 3, 5, '서은혁', [4, 5, 6, '고양이'], 4, 5, 6, '고양이']

In [88]:
list2[4]

[4, 5, 6, '고양이']

In [89]:
list2[5]

4

In [91]:
list4 = [39, 10, 18, 45]

In [92]:
list4

[39, 10, 18, 45]

In [93]:
list4.sort()

In [94]:
list4

[10, 18, 39, 45]

In [95]:
del list2[4]

In [96]:
list2

[2, 3, 5, '서은혁', 4, 5, 6, '고양이']

tuple

In [104]:
ex1 = (1, "서은혁", 3)

In [105]:
ex1

(1, '서은혁', 3)

In [106]:
ex1[-1]

3

In [107]:
ex1[-1] = "코끼리"

TypeError: 'tuple' object does not support item assignment

In [108]:
ex1.append(3)

AttributeError: 'tuple' object has no attribute 'append'

array

In [109]:
import numpy

In [110]:
ex2 = numpy.array([1,2,3])

In [111]:
ex2

array([1, 2, 3])

In [115]:
type(ex2)

numpy.ndarray

In [116]:
list4

[10, 18, 39, 45]

In [117]:
list4+1

TypeError: can only concatenate list (not "int") to list

In [118]:
ex2+1

array([2, 3, 4])

In [120]:
numpy.log(100)

4.605170185988092

In [121]:
numpy.sqrt(100)

10.0

In [122]:
import numpy as np

In [123]:
np.sqrt(100)

10.0

In [124]:
np.log(10000)

9.210340371976184

In [2]:
from numpy import array

In [3]:
ex3 = numpy.array([2,3,4])

NameError: name 'numpy' is not defined

In [4]:
ex3 = array([2,3,4])

In [5]:
ex3

array([2, 3, 4])

In [8]:
import math

In [9]:
math.pi

3.141592653589793

In [10]:
math.sin(math.pi*0.5)

1.0

In [11]:
import numpy as np

In [12]:
np.exp(3)

20.085536923187668

In [23]:
np.random.randn()

0.675658890356799

In [24]:
from datetime import datetime, timedelta

In [26]:
today = datetime.now()

In [27]:
today.year

2020

In [28]:
today.month

11

In [29]:
today.day

1

In [34]:
day_ex = datetime(2020,11,1)

In [35]:
yesterday = datetime(day_ex.year, day_ex.month, day_ex.day-1)

ValueError: day is out of range for month

In [39]:
yesterday = day_ex - timedelta(days=1)

In [40]:
yesterday

datetime.datetime(2020, 10, 31, 0, 0)

In [47]:
from workalendar.asia import SouthKorea

In [48]:
cal = SouthKorea()
cal.holidays(2020)

[(datetime.date(2020, 1, 1), 'New year'),
 (datetime.date(2020, 1, 24), "Korean New Year's Day"),
 (datetime.date(2020, 1, 25), "Korean New Year's Day"),
 (datetime.date(2020, 1, 26), "Korean New Year's Day"),
 (datetime.date(2020, 3, 1), 'Independence Day'),
 (datetime.date(2020, 4, 30), "Buddha's Birthday"),
 (datetime.date(2020, 5, 5), "Children's Day"),
 (datetime.date(2020, 6, 6), 'Memorial Day'),
 (datetime.date(2020, 8, 15), 'Liberation Day'),
 (datetime.date(2020, 9, 30), 'Midautumn Festival'),
 (datetime.date(2020, 10, 1), 'Midautumn Festival'),
 (datetime.date(2020, 10, 2), 'Midautumn Festival'),
 (datetime.date(2020, 10, 3), 'National Foundation Day'),
 (datetime.date(2020, 10, 9), 'Hangul Day'),
 (datetime.date(2020, 12, 25), 'Christmas Day')]

In [54]:
dict1 = {'apple' : apple, 'ibm' : ibm}

In [55]:
dict1['이름']

['김정우', '서은혁']